# Generated by Django 5.1.7 on 2025-04-04 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_articleimage_article_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 250 сим.', max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('slug', models.SlugField(unique_for_date='pub_date', verbose_name='Слаг')),
                ('main_page', models.BooleanField(default=True, help_text='Показувати на головній сторінці', verbose_name='Головна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Фото')),
                ('title', models.CharField(blank=True, help_text='Максимум 250 сим.', max_length=250, verbose_name='Заголовок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Фото для статті',
                'verbose_name_plural': 'Фото для статті',
            },
        ),
    ]
