# Generated by Django 5.1.7 on 2025-04-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
    ]
